version: '3.8'

services:
  idp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idp_provider
    ports:
      - "${PORT:-5000}:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  idp_db:
    image: postgres:latest
    container_name: idp_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: records
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: